### ISSUE TITLE
ENHANCEMENT: Export Results Feature

### ISSUE THREAD

**Issue by dylandavispc** [SSAgov/ANDI#129] opened 2022-02-21 14:36 UTC
Hello SSA Team,

My name is Dylan Davis a web developer who commonly uses the ANDI 508 “favelet”.

I was wondering if your team had thought about adding an export feature to the ANDI tool that exports the page results at an excel file?

We commonly have to do this by hand in my team and this increase our quality of work greatly.

As I said I am a developer with experience in HTML, CSS, JavaScript, and jQuery.  Since the tool is open-sourced I would be willing to implement this feature.

Thanks

**Comment by JohnCotterSSA** [comment] 2022-02-22 14:50
Duplicate of #117

**Comment by JohnCotterSSA** [comment] 2022-02-22 14:51
Thanks for your interest in ANDI. There are many commercially available tools for automated testing. Our focus for ANDI is manual code inspection and we have no plans to support an automated test reporting feature.

**Closed** 2022-02-22 14:51 UTC
