### ISSUE TITLE
ANDI's icons not showing in any browser for some websites

### ISSUE THREAD

**Issue by cedarwaxwing** [SSAgov/ANDI#59] opened 2019-12-18 16:00 UTC
I have ANDI installed on Firefox, Chrome and Edge and when I select the ANDI bookmarklet ANDI opens, but none of the icons appear in the ANDI application on _some_ websites. They show on most websites, but not some of the sites I am testing. On most websites the icons show, but on these (under the same domain name) the icons do not. I have tried two different laptops with the same result.
![2019-12-18_10-25-33](https://user-images.githubusercontent.com/10695608/71099881-04e80100-2182-11ea-8e80-363009a79ae5.jpg)

**Comment by JohnCotterSSA** [comment] 2020-01-13 12:23
This probably has to do with the application's CSS overriding ANDI's CSS. If you can provide some sample links, we can reproduce the issue and look into increasing the specificity of the CSS definitions.

**Comment by cedarwaxwing** [comment] 2020-07-28 18:17
I just saw this -- very sorry for the late response. Here is a link where ANDI looks odd: https://www.childwelfare.gov/. Also https://www.childwelfare.gov/topics/adoption/nam/

**Comment by JohnCotterSSA** [comment] 2020-07-29 14:01
Thanks for the links. We've verified the issue and will look into the possibility of a resolution.

**Comment by JohnCotterSSA** [comment] 2020-07-29 14:08
It looks like the issue is occurring because the test site is blocking images that violates its Content Security Policy.

Taking a look at the Console in the Developer Tools, you will see this error:
![image](https://user-images.githubusercontent.com/55763887/88810097-e66bce80-d182-11ea-8613-055cabeb6df2.png)

This appears to be a graphical issue only - all other ANDI features appear to work.

The issue cannot be resolved within ANDI's code. Options for resolving the issue can be found in the first bullet point located here: https://www.ssa.gov/accessibility/andi/help/faq.html#wontLaunch

**Closed by JohnCotterSSA** 2020-07-29 14:08 UTC
Labels: bug
